// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using artgallery_server.Infrastructure;

#nullable disable

namespace artgallery_server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106150138_ChangeArtIdToInt")]
    partial class ChangeArtIdToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("artgallery_server.Models.Abstract.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("artgallery_server.Models.Art", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Arts");
                });

            modelBuilder.Entity("artgallery_server.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("artgallery_server.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("artgallery_server.Models.Exhibitions.Exhibition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exhibitions");
                });

            modelBuilder.Entity("artgallery_server.Models.Exhibitions.ExhibitionArt", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WallLocation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("ExhibitionId", "ArtId");

                    b.HasIndex("ArtId");

                    b.ToTable("ExhibitionArts");
                });

            modelBuilder.Entity("artgallery_server.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("artgallery_server.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArtId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("artgallery_server.Models.Tag.ArtTag", b =>
                {
                    b.Property<int>("ArtId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArtTags");
                });

            modelBuilder.Entity("artgallery_server.Models.Tag.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("artgallery_server.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExhibitionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExhibitionId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("artgallery_server.Models.Admin", b =>
                {
                    b.HasBaseType("artgallery_server.Models.Abstract.User");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("artgallery_server.Models.Customer", b =>
                {
                    b.HasBaseType("artgallery_server.Models.Abstract.User");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAdress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("artgallery_server.Models.Art", b =>
                {
                    b.HasOne("artgallery_server.Models.Artist", "Artist")
                        .WithMany("Arts")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("artgallery_server.Models.Category", "Category")
                        .WithMany("Arts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("artgallery_server.Models.Category", b =>
                {
                    b.HasOne("artgallery_server.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("artgallery_server.Models.Exhibitions.ExhibitionArt", b =>
                {
                    b.HasOne("artgallery_server.Models.Art", "Art")
                        .WithMany("ExhibitionArts")
                        .HasForeignKey("ArtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("artgallery_server.Models.Exhibitions.Exhibition", "Exhibition")
                        .WithMany("ExhibitionArts")
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Art");

                    b.Navigation("Exhibition");
                });

            modelBuilder.Entity("artgallery_server.Models.Order", b =>
                {
                    b.HasOne("artgallery_server.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("artgallery_server.Models.OrderItem", b =>
                {
                    b.HasOne("artgallery_server.Models.Art", "Art")
                        .WithMany()
                        .HasForeignKey("ArtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("artgallery_server.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Art");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("artgallery_server.Models.Tag.ArtTag", b =>
                {
                    b.HasOne("artgallery_server.Models.Art", "Art")
                        .WithMany("ArtTags")
                        .HasForeignKey("ArtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("artgallery_server.Models.Tag.Tag", "Tag")
                        .WithMany("ArtTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Art");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("artgallery_server.Models.Ticket", b =>
                {
                    b.HasOne("artgallery_server.Models.Exhibitions.Exhibition", "Exhibition")
                        .WithMany("Tickets")
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("artgallery_server.Models.Abstract.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exhibition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("artgallery_server.Models.Admin", b =>
                {
                    b.HasOne("artgallery_server.Models.Abstract.User", null)
                        .WithOne()
                        .HasForeignKey("artgallery_server.Models.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("artgallery_server.Models.Customer", b =>
                {
                    b.HasOne("artgallery_server.Models.Abstract.User", null)
                        .WithOne()
                        .HasForeignKey("artgallery_server.Models.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("artgallery_server.Models.Art", b =>
                {
                    b.Navigation("ArtTags");

                    b.Navigation("ExhibitionArts");
                });

            modelBuilder.Entity("artgallery_server.Models.Artist", b =>
                {
                    b.Navigation("Arts");
                });

            modelBuilder.Entity("artgallery_server.Models.Category", b =>
                {
                    b.Navigation("Arts");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("artgallery_server.Models.Exhibitions.Exhibition", b =>
                {
                    b.Navigation("ExhibitionArts");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("artgallery_server.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("artgallery_server.Models.Tag.Tag", b =>
                {
                    b.Navigation("ArtTags");
                });

            modelBuilder.Entity("artgallery_server.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
